FROM golang:1.18 as builder
MAINTAINER user<user@example.com>
ENV GO111MODULE=on \
    GOPROXY=https://goproxy.cn,direct
WORKDIR $GOPATH/src/GrpcProject
# 将当前目录同步到docker工作目录下
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main .
FROM scratch
MAINTAINER user<user@example.com>
ENV GIN_MOD=release
WORKDIR /DockerTest
COPY --from=builder /go/src/GrpcProject/main .
EXPOSE 8080
ENTRYPOINT ["./main"]
